<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS0d8MRZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS0d8MRZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS0d8MRZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS0d8MRZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS0d8MRZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'S0d8MRZ',
    'container.build_id' => 'a9ace36b',
    'container.build_time' => 1580659760,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS0d8MRZ');
